In [1]:
# pip install selenium webdriver-manager

In [2]:
print(1)

1

In [3]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

# Corrigido aqui 👇
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)

In [4]:
# lista = [1]
# for i in lista:
#     # Abre o site
#     # driver.get("https://www.reclameaqui.com.br/empresa/itau/lista-reclamacoes/")
#     driver.get(f"https://www.reclameaqui.com.br/empresa/itau/lista-reclamacoes/?pagina=6")

#     # Espera carregar
#     time.sleep(5)

#     # Pega elementos
#     titulos = driver.find_elements(By.TAG_NAME, "a")

#     dados = []

#     for t in titulos:
#         texto = t.text
#         if texto:
#             dados.append({"titulo": texto})

#         # filtra só textos maiores (evita lixo)
#         if texto and len(texto) > 100:
#             dados.append({"titulo": texto})

#     # Fecha navegador
#     driver.quit()

In [ ]:
# # Salva CSV
# df = pd.DataFrame(dados)
# palavras_ruins = [
#     # anteriores
#     "Home"
#     ,"Sobre"
#     ,"FAQ"
#     ,"Posts"
#     ,"Compare"
#     ,"Descontos"
#     ,"Reclamar"
#     ,"RA Ads"
#     ,"Saiba mais"
#     ,"Área do consumidor",
#     "Cadastrar empresa"
#     ,"Buscar descontos"
#     ,"Rankings"
#     ,"Melhores empresas"
#     ,"Minhas Reclamações"
#     ,"Detector de Site Confiável"

#     # novos que você mandou
#     ,"Ler reclamação completa",
#     "Faça uma reclamação",
#     "Compare empresas",
#     "Cadastre uma empresa",
#     "Área da empresa",
#     "Por que estar AQUI?",
#     "Responder reclamações",
#     "Meus Produtos Reclame AQUI",
#     "acesse aqui",
#     "Institucional",
#     "Fale conosco",
#     "RA Educa",
#     "Conheca a extensão",
#     "Prêmio",
#     "Blog RA",
#     "Reclamar de uma empresa",
#     "Quero trocar minha senha",
#     "Não encontrei uma empresa",
#     "Reclamei e ainda não responderam",
#     "Quero cadastrar uma empresa",
#     "Fale com o Reclame AQUI",
#     "Termos de uso",
#     "Política de privacidade",
#     "Reclamações",
#     "Principais problemas",
#     "Banco Itaú",
#     "Bancos e Financeiras - Bancos Tradicionais e D...",
#     "+ 1.8 milhão de visualizações",
#     "Ótimo",
#     "Verificada"
#     ,"Entenda como calculamos a reputação"
#     ,"Política de Privacidade"
#     ,"B"
#     ,"Minhas reclamações"
#     ,"Crie sua conta"
#     ,"Ranking"
#     ,"Tire suas dúvidas sobre o Reclame AQUI"

# ]

# df = df[~df["titulo"].isin(palavras_ruins)]
# display(df.head(50))

                                               titulo
6   Bancos e Financeiras - Bancos Tradicionais e D...
21  Serasa: Cobrança de dívidas prescritas e condi...
23  Cobrança indevida de LIS: cliente alega não te...
27  Cartão Uniclass Black apresenta "Modo Inválido...
28  Cartão Uniclass Black apresenta "Modo Inválido...
30                                 Cobrança indevida.

### Segunda Parte

In [5]:
import time
import random
import undetected_chromedriver as uc

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import StaleElementReferenceException

driver = uc.Chrome(version_main=148)
wait = WebDriverWait(driver, 15)

dados = []

try:
    for pagina in range(2, 10):

        url = f"https://www.reclameaqui.com.br/empresa/consorcio-fiat-e-itau/lista-reclamacoes/?pagina={pagina}"
        print(f"Acessando página {pagina}...")

        driver.get(url)

        wait.until(
            EC.presence_of_all_elements_located((By.TAG_NAME, "a"))
        )

        time.sleep(random.uniform(3, 6))

        elementos = driver.find_elements(By.TAG_NAME, "a")

        for i in range(len(elementos)):
            try:
                # 🔥 rebusca o elemento pelo índice
                elementos = driver.find_elements(By.TAG_NAME, "a")
                texto = elementos[i].text.strip()

                if texto and len(texto) > 40:
                    dados.append({"titulo": texto})

            except StaleElementReferenceException:
                # ignora e segue
                continue

        print(f"Página {pagina} coletada. Total até agora: {len(dados)}")

        time.sleep(random.uniform(5, 10))

finally:
    driver.quit()
print(f"\nTotal coletado: {len(dados)}")

Acessando página 2...
Página 2 coletada. Total até agora: 4

KeyboardInterrupt:

In [ ]:
# Salva CSV
df = pd.DataFrame(dados)
palavras_ruins = [
    # anteriores
    "Home"
    ,"Sobre"
    ,"FAQ"
    ,"Posts"
    ,"Compare"
    ,"Descontos"
    ,"Reclamar"
    ,"RA Ads"
    ,"Saiba mais"
    ,"Área do consumidor",
    "Cadastrar empresa"
    ,"Buscar descontos"
    ,"Rankings"
    ,"Melhores empresas"
    ,"Minhas Reclamações"
    ,"Detector de Site Confiável"

    # novos que você mandou
    ,"Ler reclamação completa",
    "Faça uma reclamação",
    "Compare empresas",
    "Cadastre uma empresa",
    "Área da empresa",
    "Por que estar AQUI?",
    "Responder reclamações",
    "Meus Produtos Reclame AQUI",
    "acesse aqui",
    "Institucional",
    "Fale conosco",
    "RA Educa",
    "Conheca a extensão",
    "Prêmio",
    "Blog RA",
    "Reclamar de uma empresa",
    "Quero trocar minha senha",
    "Não encontrei uma empresa",
    "Reclamei e ainda não responderam",
    "Quero cadastrar uma empresa",
    "Fale com o Reclame AQUI",
    "Termos de uso",
    "Política de privacidade",
    "Reclamações",
    "Principais problemas",
    "Banco Itaú",
    "Bancos e Financeiras - Bancos Tradicionais e D...",
    "+ 1.8 milhão de visualizações",
    "Ótimo",
    "Verificada"
    ,"Entenda como calculamos a reputação"
    ,"Política de Privacidade"
    ,"B"
    ,"Minhas reclamações"
    ,"Crie sua conta"
    ,"Ranking"
    ,"Tire suas dúvidas sobre o Reclame AQUI"

]

df = df[~df["titulo"].isin(palavras_ruins)]
display(df.head(50))

                                               titulo
0   Demora excessiva e falta de informação no proc...
1   Cobrança Indevida e Falta de Resposta Após Can...
2   Itaú Unibanco / Consórcio Itaú: Recusa de Tran...
3   Consórcio Itaú recusa todo mundo - sistema de ...
4   Cobrança indevida de valores não autorizados e...
5   Solicitação de cancelamento de consórcio, títu...
6   Cobrança Indevida e Falta de Informação Clara ...
7          Não enviam o boleto de consórcio por email
8   Reembolso de valor pago não realizado, descump...
9   Problemas de visualização de lance no aplicati...
10  Saldo Devedor Incorreto em Consórcio Imobiliár...
11          Comprovante pagamento consórcio automóvel
12  Impossibilidade de obter declaração de parcela...
13  Reclamação sobre carro com múltiplos defeitos ...
14  Viúva tenta receber valor de consórcio após fa...
15        Consórcio - uso do saldo restante do carro.
16  Itaú Consórcios se recusa a fornecer cópia do ...
17  Informações divergentes sobre utilização de ca...
18  Consórcio Itaú: Desistência em ***** e Não Dev...
19  Valor de restituição de consórcio cancelado mu...
20  Transferência de titularidade de consórcio de ...
21  Consórcio Itaú: Erro no sistema impede uso de ...
22  Banco Itaú: Cobrança Indevida e Falta de Estor...
23  Dificuldade em obter contrato de consórcio imo...
24  Empresa engana clientes com promessas de inves...
25  Demora no envio do boleto de consórcio demoran...
26  Consórcio Itaú: Cobrança Indevida de 50% em Ca...

### Código pronto

In [ ]:
import time
import random
import undetected_chromedriver as uc

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import StaleElementReferenceException

driver = uc.Chrome(version_main=148)
wait = WebDriverWait(driver, 15)

dados = []

try:
    for pagina in range(2, 3):

        url = f"https://www.reclameaqui.com.br/empresa/consorcio-fiat-e-itau/lista-reclamacoes/?pagina={pagina}"
        print(f"Acessando página {pagina}...")

        driver.get(url)

        wait.until(
            EC.presence_of_all_elements_located((By.TAG_NAME, "a"))
        )

        time.sleep(random.uniform(3, 6))

        elementos = driver.find_elements(By.TAG_NAME, "a")

        for i in range(len(elementos)):
            try:
                # 🔥 rebusca o elemento pelo índice
                elementos = driver.find_elements(By.TAG_NAME, "a")
                texto = elementos[i].text.strip()
                link = elementos[i].get_attribute("href")

                # spans = driver.find_elements(By.TAG_NAME, "span")
                # texto_span = spans[i].text.strip()
                # if texto_span and "há" in texto_span.lower():


                if texto and len(texto) > 40 and link:
                    dados.append({
                        "titulo": texto,
                        "link": link
                    })

            except StaleElementReferenceException:
                # ignora e segue
                continue

        print(f"Página {pagina} coletada. Total até agora: {len(dados)}")

        time.sleep(random.uniform(5, 10))

finally:
    driver.quit()
print(f"\nTotal coletado: {len(dados)}")

Acessando página 2...
Página 2 coletada. Total até agora: 4

Total coletado: 4

In [10]:
df = pd.DataFrame(dados)
df

,titulo,link
0,Demora excessiva e falta de informação no proc...,https://www.reclameaqui.com.br/consorcio-fiat-...
1,Cobrança Indevida e Falta de Resposta Após Can...,https://www.reclameaqui.com.br/consorcio-fiat-...
2,Itaú Unibanco / Consórcio Itaú: Recusa de Tran...,https://www.reclameaqui.com.br/consorcio-fiat-...
3,Consórcio Itaú recusa todo mundo - sistema de ...,https://www.reclameaqui.com.br/consorcio-fiat-...

In [11]:
lista = df['link'].to_list()
lista

['https://www.reclameaqui.com.br/consorcio-fiat-e-itau/demora-excessiva-e-falta-de-informacao-no-processo-de-transferencia-de-titularidade-de-consorcio-resultando-em-risco-de-perda-de-negocio_I4xiLCnb0Tc8Uqfx/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/cobranca-indevida-e-falta-de-resposta-apos-cancelamento-de-consorcio-itau_T2RMN2V4KxzQJ1r8/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/itau-unibanco-consorcio-itau-recusa-de-transferencia-de-cotas-contempladas-sem-justificativa-plausivel-e-falta-de-resolucao_CMwamVZDsohoRBZB/',
 'https://www.reclameaqui.com.br/consorcio-fiat-e-itau/consorcio-itau-recusa-todo-mundo-sistema-de-analise-de-credito-bugado_q3_1BafRx-S8E3Eg/']